alter table NEWREPORTTEST_REF_ENTITY add constraint FK_NEWREPORTTEST_REF_ENTITY_AUTHOR foreign key (AUTHOR_ID) references NEWREPORTTEST_AUTHOR(ID);
alter table NEWREPORTTEST_REF_ENTITY add constraint FK_NEWREPORTTEST_REF_ENTITY_BOOK foreign key (BOOK_ID) references NEWREPORTTEST_BOOK(ID);
create index IDX_NEWREPORTTEST_REF_ENTITY_AUTHOR on NEWREPORTTEST_REF_ENTITY (AUTHOR_ID);
create index IDX_NEWREPORTTEST_REF_ENTITY_BOOK on NEWREPORTTEST_REF_ENTITY (BOOK_ID);
