alter table NEWREPORTTEST_REF_ENTITY add constraint FK_NEWREPORTTEST_REF_ENTITY_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID);
create index IDX_NEWREPORTTEST_REF_ENTITY_IMAGE on NEWREPORTTEST_REF_ENTITY (IMAGE_ID);
