alter table NEWREPORTTEST_NEW_ENTITY add constraint FK_NEWREPORTTEST_NEW_ENTITY_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_NEWREPORTTEST_NEW_ENTITY_FILE on NEWREPORTTEST_NEW_ENTITY (FILE_ID);
