alter table NEWREPORTTEST_BOOK add constraint FK_NEWREPORTTEST_BOOK_LITERATURE_TYPE foreign key (LITERATURE_TYPE_ID) references NEWREPORTTEST_LITERATURE_TYPE(ID);
alter table NEWREPORTTEST_BOOK add constraint FK_NEWREPORTTEST_BOOK_AUTHOR foreign key (AUTHOR_ID) references NEWREPORTTEST_AUTHOR(ID);
create index IDX_NEWREPORTTEST_BOOK_LITERATURE_TYPE on NEWREPORTTEST_BOOK (LITERATURE_TYPE_ID);
create index IDX_NEWREPORTTEST_BOOK_AUTHOR on NEWREPORTTEST_BOOK (AUTHOR_ID);
